

#언어(플램폿)선택
language: generic 

#도커 환경 구성
services:
  - docker

#스크립트를 실행할 수 있는 환경
before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t test/react-docker -f Dockerfile.dev .

#실행할 스크립트
script:
  - docker run -e CI=true test/react-docker npm run test -- --coverage

#테스트 성공 후 
after_success:
  - echo "Test Success"