sudo: required

language: generic

services:
  - docker

before_install: 
  - echo "start creating an image with dockerfile"
  - docker build -t test/docker-reac-app -f Dockerfile.dev .

script:
  - docker run -e CI=true test/docker-reac-app npm run test -- --coverage

after_success:
  - echo "test success"